(function(){
 'use strict'; if(!window.SDAuth.require())return;
 const {api,money,esc,dateOnly,toast,loading}=window.SD,page=document.body.dataset.page||'dashboard';
 const titles={dashboard:'Dashboard',bookings:'Bookings',calendar:'Calendar',vehicles:'Vehicles',payments:'Payments',customers:'Customers',reports:'Reports',settings:'Settings'};
 const icons={dashboard:'⌂',bookings:'▤',calendar:'□',vehicles:'▰',payments:'$',customers:'♙',reports:'↗',settings:'⚙'};
 const user=JSON.parse(localStorage.getItem('sd_admin_user')||'{}');
 const app=document.getElementById('admin-app');
 app.className=`admin-layout ${localStorage.getItem('sd_sidebar_collapsed')==='1'?'collapsed':''}`;
 app.innerHTML=`<aside class="sidebar"><a class="brand" id="side-logo"><span class="brand-mark">S&D</span><span class="brand-text">EXPRESS<small>Delivery Service</small></span></a><nav class="side-nav">${Object.keys(titles).map(k=>`<a href="${k}.html" class="${page===k?'active':''}" title="${titles[k]}"><span class="nav-icon">${icons[k]}</span><span class="nav-label">${titles[k]}</span></a>`).join('')}</nav></aside><main class="admin-main"><header class="topbar"><div class="topbar-left"><button class="hamburger" id="hamburger">☰</button><div><small style="color:var(--muted)">Operations</small><h1>${titles[page]}</h1></div></div><div class="admin-user"><div class="avatar">${esc((user.email||'A')[0].toUpperCase())}</div><span><strong style="display:block;font-size:12px">${esc(user.email||'Administrator')}</strong><button id="logout" style="border:0;background:none;padding:0;color:var(--muted);font-size:10px;cursor:pointer">Sign out</button></span></div></header><div class="admin-content" id="content"><div class="empty"><span class="spinner"></span><b>Loading ${titles[page].toLowerCase()}…</b></div></div></main>`;
 document.getElementById('side-logo').onclick=()=>{if(innerWidth<=760)app.classList.remove('mobile-open');else{app.classList.toggle('collapsed');localStorage.setItem('sd_sidebar_collapsed',app.classList.contains('collapsed')?'1':'0')}};
 document.getElementById('hamburger').onclick=()=>app.classList.toggle('mobile-open');app.addEventListener('click',e=>{if(innerWidth<=760&&app.classList.contains('mobile-open')&&!e.target.closest('.sidebar')&&!e.target.closest('#hamburger'))app.classList.remove('mobile-open')});document.getElementById('logout').onclick=window.SDAuth.logout;
 const content=document.getElementById('content'), slug=s=>String(s||'').toLowerCase().replaceAll(' ','-');
 const badge=(value)=>`<span class="badge status-${slug(value)}">${esc(value)}</span>`;
 const modal=(title,body,foot='')=>{const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><button class="modal-close">×</button></div><div class="modal-body">${body}</div>${foot?`<div class="modal-foot">${foot}</div>`:''}</div>`;wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('.modal-close'))wrap.remove()});document.body.append(wrap);return wrap};
 const safe=fn=>async(...args)=>{try{await fn(...args)}catch(e){toast(e.message,'error')}};
 let state={bookings:[],vehicles:[],customers:[],payments:[],settings:{}};
 const normalizeImageUrl=value=>{
  const raw=String(value||'').trim();
  if(!raw)return '';
  try{
   const url=new URL(raw);
   if(url.protocol!=='https:'&&url.protocol!=='http:')return '';
   if(url.hostname==='drive.google.com'){
    const fileMatch=url.pathname.match(/\/file\/d\/([^/]+)/);
    const id=(fileMatch&&fileMatch[1])||url.searchParams.get('id');
    if(id)return `https://drive.google.com/uc?export=view&id=${encodeURIComponent(id)}`;
   }
   return url.href;
  }catch{return ''}
 };
 const vehicleArt=v=>{
  const src=normalizeImageUrl(v.imageUrl);
  const fallback=`<svg class="vehicle-fallback" viewBox="0 0 700 320"><use href="../assets/fleet.svg#${String(v.type).toLowerCase().includes('bus')?'bus':'van'}"/></svg>`;
  return src?`<img class="vehicle-photo" src="${esc(src)}" alt="${esc(v.vehicleName)}">${fallback}`:fallback;
 };
 async function dashboard(){const d=await api('GET_DASHBOARD',{},'GET');content.innerHTML=`<div class="metric-grid">${[['Today’s bookings',d.todayBookings,'▤'],['Upcoming trips',d.upcomingTrips,'→'],['Monthly revenue',money(d.monthlyRevenue),'↗'],['Paid amount',money(d.paidAmount),'✓'],['Pending payment',money(d.pendingAmount),'◷'],['Available vehicles',d.availableVehicles,'▰']].map(x=>`<article class="metric"><div class="metric-top"><span>${x[0]}</span><span class="metric-icon">${x[2]}</span></div><strong>${x[1]}</strong><small>Live operations data</small></article>`).join('')}</div><div class="content-grid"><section class="panel"><div class="panel-head"><h2>Monthly revenue</h2><a href="reports.html" class="btn btn-outline btn-sm">View report</a></div>${chart(d.revenueChart)}</section><section class="panel"><div class="panel-head"><h2>Recent activity</h2></div><div class="activity-list">${d.recentBookings.length?d.recentBookings.map(b=>`<div class="activity"><div><p><strong>${esc(b.customerName)}</strong> created ${esc(b.bookingId)}</p><small>${dateOnly(b.createdDate)} · ${esc(b.vehicleName)}</small></div>${badge(b.bookingStatus)}</div>`).join(''):'<div class="empty">No bookings yet.</div>'}</div></section></div><section class="panel" style="margin-top:18px"><div class="panel-head"><h2>Upcoming journeys</h2><a href="bookings.html">View all →</a></div>${bookingTable(d.upcomingBookings,false)}</section>`}
 function chart(items=[]){const max=Math.max(...items.map(x=>+x.value),1);return `<div class="chart">${items.map(x=>`<div class="bar" style="height:${Math.max(3,+x.value/max*100)}%" data-value="${money(x.value)}"></div>`).join('')}</div><div class="chart-labels">${items.map(x=>`<span>${esc(x.label)}</span>`).join('')}</div>`}
 function bookingTable(rows,actions=true){return rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Booking ID</th><th>Customer</th><th>Vehicle</th><th>Pickup</th><th>Return</th><th>Amount</th><th>Payment</th><th>Status</th>${actions?'<th>Action</th>':''}</tr></thead><tbody>${rows.map(b=>`<tr><td><a href="#" data-view="${esc(b.bookingId)}">${esc(b.bookingId)}</a></td><td><strong>${esc(b.customerName)}</strong><br><small>${esc(b.phone)}</small></td><td>${esc(b.vehicleName)}</td><td>${dateOnly(b.pickupDate)}</td><td>${dateOnly(b.returnDate)}</td><td>${money(b.totalAmount)}</td><td>${badge(b.paymentStatus)}</td><td>${badge(b.bookingStatus)}</td>${actions?`<td><div class="actions"><button class="icon-action" data-edit="${esc(b.bookingId)}" title="Edit">✎</button><button class="icon-action" data-quote="${esc(b.bookingId)}" title="Quotation">QT</button><button class="icon-action" data-invoice="${esc(b.bookingId)}" title="Invoice">INV</button><button class="icon-action" data-delete="${esc(b.bookingId)}" title="Delete">×</button></div></td>`:''}</tr>`).join('')}</tbody></table></div>`:'<div class="empty">▤<b>No bookings found</b>New bookings will appear here.</div>'}
 async function bookings(){state.bookings=await api('GET_BOOKINGS',{},'GET');content.innerHTML=`<div class="toolbar"><div class="search-wrap"><input class="search-input" id="booking-search" placeholder="Search booking ID, customer or phone…"></div><select id="status-filter"><option value="">All statuses</option>${['New Inquiry','Quotation Sent','Waiting Deposit','Payment Review','Confirmed','On Trip','Completed','Cancelled'].map(x=>`<option>${x}</option>`).join('')}</select><button class="btn btn-primary btn-sm" id="refresh">Refresh</button></div><section class="panel" id="booking-table">${bookingTable(state.bookings)}</section>`;const apply=()=>{const q=document.getElementById('booking-search').value.toLowerCase(),s=document.getElementById('status-filter').value;document.getElementById('booking-table').innerHTML=bookingTable(state.bookings.filter(b=>(!s||b.bookingStatus===s)&&[b.bookingId,b.customerName,b.phone,b.vehicleName].join(' ').toLowerCase().includes(q)))};document.getElementById('booking-search').oninput=apply;document.getElementById('status-filter').onchange=apply;document.getElementById('refresh').onclick=()=>loadPage()}
 function bookingView(b){return `<div class="summary-list"><div class="summary-row"><span>Customer</span><strong>${esc(b.customerName)} · ${esc(b.phone)}</strong></div><div class="summary-row"><span>Vehicle</span><strong>${esc(b.vehicleName)}</strong></div><div class="summary-row"><span>Date</span><strong>${dateOnly(b.pickupDate)} – ${dateOnly(b.returnDate)}</strong></div><div class="summary-row"><span>Route</span><strong>${esc(b.pickupLocation)} → ${esc(b.dropLocation)}</strong></div><div class="summary-row"><span>Trip / passengers</span><strong>${esc(b.tripType)} · ${esc(b.passenger)}</strong></div><div class="summary-row"><span>Amount</span><strong>${money(b.totalAmount)}</strong></div><div class="summary-row"><span>Payment</span>${badge(b.paymentStatus)}</div><div class="summary-row"><span>Booking</span>${badge(b.bookingStatus)}</div><div><span style="color:var(--muted);font-size:12px">Notes</span><p>${esc(b.customerNotes||b.adminNotes||'No notes')}</p></div></div>`}
 function editBooking(b){const statuses=['New Inquiry','Quotation Sent','Waiting Deposit','Payment Review','Confirmed','On Trip','Completed','Cancelled'];const pays=['Pending','Waiting Payment','Waiting Verification','Paid','Rejected'];const m=modal(`Edit ${b.bookingId}`,`<form id="edit-booking" class="field-grid"><div class="field"><label>Booking status</label><select name="bookingStatus">${statuses.map(x=>`<option ${b.bookingStatus===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Payment status</label><select name="paymentStatus">${pays.map(x=>`<option ${b.paymentStatus===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Additional charges</label><input name="additionalCharges" type="number" min="0" step="0.01" value="${+b.additionalCharges||0}"></div><div class="field"><label>Discount</label><input name="discount" type="number" min="0" step="0.01" value="${+b.discount||0}"></div><div class="field full"><label>Admin notes</label><textarea name="adminNotes">${esc(b.adminNotes||'')}</textarea></div></form>`,`<button class="btn btn-outline modal-close">Cancel</button><button class="btn btn-primary" id="save-booking">Save changes</button>`);m.querySelector('#save-booking').onclick=safe(async e=>{const fd=Object.fromEntries(new FormData(m.querySelector('form')));loading(e.currentTarget,true,'Saving…');await api('UPDATE_BOOKING',{bookingId:b.bookingId,updates:fd});toast('Booking updated.','success');m.remove();loadPage()})}
 async function calendar(){state.bookings=await api('GET_BOOKINGS',{},'GET');let cursor=new Date();cursor.setDate(1);function draw(){const y=cursor.getFullYear(),mo=cursor.getMonth(),first=new Date(y,mo,1),start=new Date(y,mo,1-first.getDay()),cells=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'),events=state.bookings.filter(b=>String(b.pickupDate).slice(0,10)<=key&&String(b.returnDate).slice(0,10)>=key&&!['Cancelled','Completed'].includes(b.bookingStatus));cells.push(`<div class="calendar-day ${d.getMonth()!==mo?'muted':''}"><strong>${d.getDate()}</strong>${events.slice(0,3).map(b=>`<div class="calendar-event" title="${esc(b.customerName)}">${esc(b.vehicleName)} · ${esc(b.customerName)}</div>`).join('')}${events.length>3?`<small>+${events.length-3} more</small>`:''}</div>`)}content.innerHTML=`<div class="panel-head"><button class="btn btn-outline btn-sm" id="cal-prev">← Previous</button><h2>${cursor.toLocaleDateString('en-MY',{month:'long',year:'numeric'})}</h2><button class="btn btn-outline btn-sm" id="cal-next">Next →</button></div><div class="calendar-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="calendar-day calendar-head">${x}</div>`).join('')}${cells.join('')}</div>`;document.getElementById('cal-prev').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);draw()};document.getElementById('cal-next').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);draw()}}draw()}
 async function vehicles(){
  state.vehicles=await api('GET_VEHICLES',{},'GET');
  content.innerHTML=`<div class="panel-head"><div><h2>Fleet overview</h2><small style="color:var(--muted)">${state.vehicles.length} registered vehicles</small></div><button class="btn btn-primary btn-sm" id="add-vehicle">+ Add vehicle</button></div><div class="vehicle-admin-grid">${state.vehicles.map((v,index)=>`<article class="vehicle-admin-card"><div class="art">${vehicleArt(v)}</div><div class="details"><div class="panel-head"><div><h3>${esc(v.vehicleName)}</h3><small>${esc(v.vehicleId)} · ${esc(v.type)}</small></div>${badge(v.status)}</div><div class="summary-row"><span>Capacity</span><strong>${esc(v.capacity)} passengers</strong></div><div class="summary-row"><span>Daily rate</span><strong>${money(v.dailyRate)}</strong></div><button class="btn btn-outline btn-sm" style="margin-top:18px" data-vehicle-index="${index}">Edit vehicle</button></div></article>`).join('')}</div>`;
  document.getElementById('add-vehicle').onclick=()=>vehicleModal();
  content.querySelectorAll('[data-vehicle-index]').forEach(button=>button.onclick=()=>vehicleModal(state.vehicles[Number(button.dataset.vehicleIndex)]));
  content.querySelectorAll('.vehicle-photo').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.nextElementSibling.hidden=false}));
 }
 function vehicleModal(v={}){
  const editing=Boolean(v&&v.vehicleId);
  const type=String(v.type||'Van').trim().toLowerCase();
  const imageUrl=normalizeImageUrl(v.imageUrl);
  const m=modal(editing?`Edit ${v.vehicleName}`:'Add vehicle',`<form id="vehicle-form" class="field-grid"><div class="field"><label>Vehicle ID</label><input name="vehicleId" required value="${esc(v.vehicleId||'')}" ${editing?'readonly':''}></div><div class="field"><label>Vehicle name</label><input name="vehicleName" required value="${esc(v.vehicleName||'')}"></div><div class="field"><label>Type</label><select name="type"><option ${type==='van'?'selected':''}>Van</option><option ${type==='bus'?'selected':''}>Bus</option></select></div><div class="field"><label>Capacity</label><input name="capacity" type="number" min="1" required value="${esc(v.capacity||'')}"></div><div class="field"><label>Daily rate (RM)</label><input name="dailyRate" type="number" min="0" step=".01" required value="${esc(v.dailyRate||'')}"></div><div class="field"><label>Status</label><select name="status">${['Available','Maintenance','Unavailable'].map(x=>`<option ${String(v.status||'Available').toLowerCase()===x.toLowerCase()?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>Image URL (optional)</label><input name="imageUrl" type="url" placeholder="https://..." value="${esc(imageUrl)}"><small>Use a direct HTTPS image URL. Google Drive sharing links are converted automatically.</small></div><div class="field full"><div class="vehicle-image-preview" id="vehicle-image-preview"><span>No image selected</span></div></div></form>`,`<button class="btn btn-outline modal-close">Cancel</button><button id="save-vehicle" class="btn btn-primary">Save vehicle</button>`);
  const input=m.querySelector('[name="imageUrl"]'),preview=m.querySelector('#vehicle-image-preview');
  const updatePreview=()=>{
   const src=normalizeImageUrl(input.value);
   preview.classList.remove('error');
   preview.innerHTML=src?`<img src="${esc(src)}" alt="Vehicle image preview">`:'<span>No image selected</span>';
   const img=preview.querySelector('img');
   if(img)img.addEventListener('error',()=>{preview.innerHTML='<span>Image could not be loaded. Check that the URL is public and points directly to an image.</span>';preview.classList.add('error')});
  };
  input.addEventListener('input',updatePreview);
  updatePreview();
  m.querySelector('#save-vehicle').onclick=safe(async e=>{
   const form=m.querySelector('form');
   if(!form.reportValidity())return;
   const vehicle=Object.fromEntries(new FormData(form));
   vehicle.imageUrl=normalizeImageUrl(vehicle.imageUrl);
   loading(e.currentTarget,true,'Saving...');
   await api('UPSERT_VEHICLE',{vehicle});
   toast(editing?'Vehicle updated.':'Vehicle added.','success');
   m.remove();
   loadPage();
  });
 }
 async function payments(){state.payments=await api('GET_PAYMENTS',{},'GET');content.innerHTML=`<section class="panel"><div class="panel-head"><h2>Payment records</h2><span class="pill">${state.payments.length} records</span></div>${state.payments.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Payment</th><th>Booking</th><th>Customer</th><th>Amount</th><th>Method</th><th>Receipt</th><th>Verification</th><th>Action</th></tr></thead><tbody>${state.payments.map(p=>`<tr><td>${esc(p.paymentId)}</td><td><a href="bookings.html?q=${esc(p.bookingId)}">${esc(p.bookingId)}</a></td><td>${esc(p.customerName||'—')}</td><td>${money(p.amount)}</td><td>${esc(p.paymentMethod)}</td><td>${esc(p.receiptStatus||'—')}</td><td>${badge(p.verificationStatus)}</td><td><button class="btn btn-sm btn-primary" data-pay="${esc(p.paymentId)}" data-status="Paid">Approve</button> <button class="btn btn-sm btn-danger" data-pay="${esc(p.paymentId)}" data-status="Rejected">Reject</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">$<b>No payments recorded</b>Add a payment from the booking workflow.</div>'}</section>`;content.querySelectorAll('[data-pay]').forEach(x=>x.onclick=safe(async()=>{await api('UPDATE_PAYMENT',{paymentId:x.dataset.pay,verificationStatus:x.dataset.status});toast(`Payment ${x.dataset.status.toLowerCase()}.`,'success');loadPage()}))}
 async function customers(){state.customers=await api('GET_CUSTOMERS',{},'GET');content.innerHTML=`<div class="toolbar"><div class="search-wrap"><input id="customer-search" class="search-input" placeholder="Search customer…"></div></div><section class="panel" id="customer-table"></section>`;const draw=()=>{const q=document.getElementById('customer-search').value.toLowerCase(),rows=state.customers.filter(c=>[c.name,c.phone,c.email].join(' ').toLowerCase().includes(q));document.getElementById('customer-table').innerHTML=rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Customer ID</th><th>Name</th><th>Contact</th><th>Total bookings</th><th>Total spending</th><th>Last booking</th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.customerId)}</td><td><strong>${esc(c.name)}</strong></td><td>${esc(c.phone)}<br><small>${esc(c.email)}</small></td><td>${esc(c.totalBooking)}</td><td>${money(c.totalSpending)}</td><td>${dateOnly(c.lastBooking)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No customers found.</div>'};draw();document.getElementById('customer-search').oninput=draw}
 async function reports(){const d=await api('GET_REPORTS',{},'GET');content.innerHTML=`<div class="metric-grid"><article class="metric"><div class="metric-top">Total revenue</div><strong>${money(d.totalRevenue)}</strong><small>Paid bookings</small></article><article class="metric"><div class="metric-top">Average booking</div><strong>${money(d.averageBooking)}</strong><small>All non-cancelled bookings</small></article><article class="metric"><div class="metric-top">Completion rate</div><strong>${esc(d.completionRate)}%</strong><small>Completed journeys</small></article></div><div class="content-grid"><section class="panel"><div class="panel-head"><h2>Revenue by month</h2></div>${chart(d.revenueChart)}</section><section class="panel"><div class="panel-head"><h2>Vehicle usage</h2></div><div class="summary-list">${d.vehicleUsage.map(v=>`<div class="summary-row"><span>${esc(v.label)}</span><strong>${esc(v.value)} bookings</strong></div>`).join('')}</div></section></div>`}
 async function settings(){state.settings=await api('GET_SETTINGS',{},'GET');const s=state.settings;content.innerHTML=`<div class="settings-grid"><nav class="settings-menu"><a class="active">Business</a><a>Payment</a><a>Notifications</a></nav><section class="panel"><div class="panel-head"><div><h2>Business & payment settings</h2><small style="color:var(--muted)">Shown on customer confirmations and documents.</small></div></div><form id="settings-form" class="field-grid"><div class="field full"><label>Business name</label><input name="businessName" value="${esc(s.businessName||'')}"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(s.phone||'')}"></div><div class="field"><label>Email</label><input type="email" name="email" value="${esc(s.email||'')}"></div><div class="field full"><label>Address</label><textarea name="address">${esc(s.address||'')}</textarea></div><div class="field"><label>Bank name</label><input name="bankName" value="${esc(s.bankName||'')}"></div><div class="field"><label>Account number</label><input name="accountNumber" value="${esc(s.accountNumber||'')}"></div><div class="field"><label>Account holder</label><input name="accountHolder" value="${esc(s.accountHolder||'')}"></div><div class="field"><label>Deposit percentage</label><input type="number" min="0" max="100" name="depositPercentage" value="${esc(s.depositPercentage||50)}"></div><div class="field full"><label>DuitNow QR image URL</label><input name="duitNowQrUrl" value="${esc(s.duitNowQrUrl||'')}"></div><div class="field full"><label>Payment terms</label><textarea name="paymentTerms">${esc(s.paymentTerms||'')}</textarea></div><div class="field full"><button class="btn btn-primary" id="save-settings">Save settings</button></div></form></section></div>`;document.getElementById('settings-form').onsubmit=safe(async e=>{e.preventDefault();const btn=document.getElementById('save-settings');loading(btn,true,'Saving…');await api('UPDATE_SETTINGS',{settings:Object.fromEntries(new FormData(e.currentTarget))});toast('Settings saved.','success');loading(btn,false)})}
 content.addEventListener('click',safe(async e=>{const target=e.target.closest('[data-view],[data-edit],[data-delete],[data-quote],[data-invoice]');if(!target)return;e.preventDefault();const id=target.dataset.view||target.dataset.edit||target.dataset.delete||target.dataset.quote||target.dataset.invoice;let b=state.bookings.find(x=>x.bookingId===id);if(!b){const rows=await api('GET_BOOKINGS',{bookingId:id},'GET');b=rows[0]}if(target.dataset.view)modal(id,bookingView(b));if(target.dataset.edit)editBooking(b);if(target.dataset.delete){if(!confirm(`Delete ${id}? This removes the booking and related payment record.`))return;await api('DELETE_BOOKING',{bookingId:id});toast('Booking deleted.','success');loadPage()}if(target.dataset.quote)window.SDInvoice.print(b,'Quotation',state.settings);if(target.dataset.invoice)window.SDInvoice.print(b,'Invoice',state.settings)}));
 async function loadPage(){content.innerHTML=`<div class="empty"><span class="spinner"></span><b>Loading ${titles[page].toLowerCase()}…</b></div>`;try{await({dashboard,bookings,calendar,vehicles,payments,customers,reports,settings}[page]||dashboard)()}catch(e){if(e.code==='UNAUTHORIZED')return window.SDAuth.logout();content.innerHTML=`<div class="empty">!<b>Unable to load ${titles[page]}</b>${esc(e.message)}<br><button id="retry" class="btn btn-primary btn-sm" style="margin-top:15px">Try again</button></div>`;document.getElementById('retry').onclick=loadPage}}
 loadPage();
})();
