(function(){
 'use strict';
 const {api,money,esc,toast,dateOnly,loading}=window.SD;
 const form=document.getElementById('booking-form');
 if(form){
  let step=1, vehicles=[], selected=null;
  const today=new Date(); today.setMinutes(today.getMinutes()-today.getTimezoneOffset());
  ['pickupDate','returnDate'].forEach(id=>document.getElementById(id).min=today.toISOString().slice(0,10));
  const fallback=[{vehicleId:'VH001',vehicleName:'Toyota Hiace 11 Seater',type:'Van',capacity:11,dailyRate:350,status:'Available'},{vehicleId:'BS001',vehicleName:'Bus 40 Seater',type:'Bus',capacity:40,dailyRate:500,status:'Available'}];
  async function loadVehicles(){
   try{vehicles=await api('GET_VEHICLES',{public:'1'},'GET');}catch(e){vehicles=fallback; if(window.SD.config.API_URL) toast(e.message,'error');}
   renderVehicles();
  }
  function renderVehicles(){
   const preferred=new URLSearchParams(location.search).get('vehicle');
   document.getElementById('vehicle-options').innerHTML=vehicles.map((v,i)=>{const available=String(v.status).toLowerCase()==='available';return `<label class="vehicle-option ${preferred===v.vehicleId&&available?'selected':''} ${available?'':'unavailable'}"><input type="radio" name="vehicleId" value="${esc(v.vehicleId)}" ${preferred===v.vehicleId&&available?'checked':''} ${available?'':'disabled'}><div class="mini-art"><svg viewBox="0 0 700 320"><use href="../assets/fleet.svg#${String(v.type).toLowerCase().includes('bus')?'bus':'van'}"/></svg></div><h3>${esc(v.vehicleName)}</h3><div class="vehicle-meta"><span>${esc(v.capacity)} passengers</span><strong>${money(v.dailyRate)}/day</strong></div><span class="pill ${available?'success':'danger'}" style="margin-top:12px">${available?'Available':'Unavailable'}</span></label>`}).join('');
   document.querySelectorAll('.vehicle-option input').forEach(r=>r.addEventListener('change',()=>{document.querySelectorAll('.vehicle-option').forEach(x=>x.classList.remove('selected'));r.closest('label').classList.add('selected');selected=vehicles.find(v=>v.vehicleId===r.value)}));
   const checked=document.querySelector('.vehicle-option input:checked'); if(checked) selected=vehicles.find(v=>v.vehicleId===checked.value);
  }
  function showStep(next){step=next;document.querySelectorAll('.wizard-panel').forEach(p=>p.classList.toggle('active',+p.dataset.panel===step));document.querySelectorAll('.step').forEach(s=>{const n=+s.dataset.step;s.classList.toggle('active',n===step);s.classList.toggle('done',n<step);if(n<step)s.querySelector('span').textContent='✓';else s.querySelector('span').textContent=n});document.getElementById('booking-wizard').scrollIntoView({behavior:'smooth',block:'start'})}
  function validPanel(){const panel=document.querySelector(`.wizard-panel[data-panel="${step}"]`);if(step===1&&!selected){toast('Please select an available vehicle.','error');return false}for(const el of panel.querySelectorAll('[required]'))if(!el.checkValidity()){el.reportValidity();return false}return true}
  function duration(){const a=new Date(document.getElementById('pickupDate').value+'T00:00:00'),b=new Date(document.getElementById('returnDate').value+'T00:00:00');return Math.max(1,Math.ceil((b-a)/86400000)+1)}
  function getData(){const fd=new FormData(form),d=Object.fromEntries(fd);d.vehicleId=selected.vehicleId;d.rentalDays=duration();d.dailyRate=+selected.dailyRate;d.subtotal=d.rentalDays*d.dailyRate;d.discount=0;d.additionalCharges=0;d.totalAmount=d.subtotal;return d}
  async function prepareReview(button){
   const pickup=document.getElementById('pickupDate').value,ret=document.getElementById('returnDate').value;if(ret<pickup){toast('Return date cannot be before pickup date.','error');return false}const pax=+document.getElementById('passenger').value;if(pax>+selected.capacity){toast(`${selected.vehicleName} can carry up to ${selected.capacity} passengers.`,'error');return false}
   if(window.SD.config.API_URL){try{loading(button,true,'Checking…');await api('CHECK_AVAILABILITY',{vehicleId:selected.vehicleId,pickupDate:pickup,returnDate:ret});}catch(e){toast(e.message,'error');return false}finally{loading(button,false)}}
   const d=getData();document.getElementById('booking-summary').innerHTML=`<div class="summary-card"><h3>Journey details</h3><div class="summary-list"><div class="summary-row"><span>Vehicle</span><strong>${esc(selected.vehicleName)}</strong></div><div class="summary-row"><span>Customer</span><strong>${esc(d.name)}</strong></div><div class="summary-row"><span>Travel date</span><strong>${dateOnly(d.pickupDate)} – ${dateOnly(d.returnDate)}</strong></div><div class="summary-row"><span>Route</span><strong>${esc(d.pickupLocation)} → ${esc(d.dropLocation)}</strong></div><div class="summary-row"><span>Passengers / type</span><strong>${esc(d.passenger)} · ${esc(d.tripType)}</strong></div></div></div><div class="summary-card summary-price"><h3>Price estimate</h3><div class="summary-list"><div class="summary-row"><span>Daily rate</span><strong>${money(d.dailyRate)}</strong></div><div class="summary-row"><span>Rental duration</span><strong>${d.rentalDays} day${d.rentalDays>1?'s':''}</strong></div><div class="summary-row total"><span>Estimated total</span><strong>${money(d.totalAmount)}</strong></div><small style="color:#aeb7c6">Final price may change if extra stops, tolls or special requirements apply.</small></div></div>`;return true
  }
  document.querySelectorAll('.next').forEach(btn=>btn.addEventListener('click',async()=>{if(!validPanel())return;if(step===3&&!(await prepareReview(btn)))return;showStep(step+1)}));
  document.querySelectorAll('.prev').forEach(btn=>btn.addEventListener('click',()=>showStep(step-1)));
  form.addEventListener('submit',async e=>{e.preventDefault();if(!document.getElementById('terms').checked)return document.getElementById('terms').reportValidity();const btn=document.getElementById('submit-booking');try{loading(btn,true,'Submitting…');const result=await api('CREATE_BOOKING',{booking:getData()});form.hidden=true;document.querySelector('.steps').hidden=true;const s=document.getElementById('booking-success');s.hidden=false;s.innerHTML=`<div class="success-icon">✓</div><h2>Booking request received</h2><p>Save your booking ID. We will contact you to confirm the journey.</p><div class="booking-id">${esc(result.bookingId)}</div><div class="payment-box"><strong>Payment instruction</strong><p>Please pay the requested deposit only after our team confirms your booking.</p><div class="summary-row"><span>Estimated deposit</span><strong>${money(result.depositAmount)}</strong></div><div class="summary-row"><span>Bank</span><strong>${esc(result.payment.bankName||'Contact us')}</strong></div><div class="summary-row"><span>Account</span><strong>${esc(result.payment.accountNumber||'—')}</strong></div><div class="summary-row"><span>Holder</span><strong>${esc(result.payment.accountHolder||result.payment.businessName||'S&D Express')}</strong></div>${result.payment.duitNowQrUrl?`<img src="${esc(result.payment.duitNowQrUrl)}" alt="DuitNow QR" style="display:block;max-width:180px;margin:18px auto">`:''}<small>Use ${esc(result.bookingId)} as your payment reference and send the receipt through WhatsApp.</small></div><div style="display:flex;justify-content:center;gap:10px;flex-wrap:wrap"><a class="btn btn-primary" href="../track/?id=${encodeURIComponent(result.bookingId)}">Track booking</a><a class="btn btn-outline" href="../">Return home</a></div>`;s.scrollIntoView({behavior:'smooth'})}catch(err){toast(err.message,'error')}finally{loading(btn,false)}});
  loadVehicles();
 }
 const trackForm=document.getElementById('track-form');
 if(trackForm){
  const param=new URLSearchParams(location.search).get('id');if(param)document.getElementById('bookingId').value=param;
  trackForm.addEventListener('submit',async e=>{e.preventDefault();const btn=document.getElementById('track-btn');try{loading(btn,true,'Searching…');const b=await api('TRACK_BOOKING',{bookingId:document.getElementById('bookingId').value.trim().toUpperCase(),phone:document.getElementById('trackPhone').value.trim()});const stages=['New Inquiry','Quotation Sent','Waiting Deposit','Payment Review','Confirmed','On Trip','Completed'],index=stages.indexOf(b.bookingStatus);document.getElementById('track-result').innerHTML=`<section class="track-result"><div class="panel-head"><div><span class="eyebrow">${esc(b.bookingId)}</span><h2 style="margin:8px 0">${esc(b.vehicleName)}</h2></div><span class="badge status-${esc(b.bookingStatus).toLowerCase().replaceAll(' ','-')}">${esc(b.bookingStatus)}</span></div><div class="summary-list"><div class="summary-row"><span>Travel date</span><strong>${dateOnly(b.pickupDate)} – ${dateOnly(b.returnDate)}</strong></div><div class="summary-row"><span>Route</span><strong>${esc(b.pickupLocation)} → ${esc(b.dropLocation)}</strong></div><div class="summary-row"><span>Estimated amount</span><strong>${money(b.totalAmount)}</strong></div><div class="summary-row"><span>Payment</span><span class="badge status-${esc(b.paymentStatus).toLowerCase().replaceAll(' ','-')}">${esc(b.paymentStatus)}</span></div></div><div class="timeline">${b.bookingStatus==='Cancelled'?`<div class="timeline-item done"><div><strong>Booking cancelled</strong><small>Please contact us if you need help.</small></div></div>`:stages.map((s,i)=>`<div class="timeline-item ${i<=index?'done':''}"><div><strong>${s}</strong><small>${i<=index?'Completed':'Pending'}</small></div></div>`).join('')}</div></section>`}catch(err){document.getElementById('track-result').innerHTML='';toast(err.message,'error')}finally{loading(btn,false)}})
 }
})();
